### ISSUE TITLE
Not creating a test network

### ISSUE THREAD

**Issue by ifeltsweet** [googleads/dfp-playground#3]
I registered a new google account then visited playground and gave my consent to the app. Next thing I see is the playground but it has not prompted me to create a test network and no network is available in dropdown. All queries return "HTTP 500 Error. Did you forget to select a network?".

**Comment by dancoates** [comment]
For anyone else coming across this issue, you can directly visit https://dfp-playground.appspot.com/make-test-network to make your test network.

**Comment by GLStephen** [comment]
@dancoates the method linked above errors out when trying to create the network

```
Internal Server Error
The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/views.py", line 231, in post
    api_handler.MakeTestNetwork()
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/utils.py", line 110, in retry_func
    return func(*args, **kwargs)
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/api_handler.py", line 68, in MakeTestNetwork
    return network_service.makeTestNetwork()
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/googleads/common.py", line 779, in MakeSoapRequest
    self._packer) for arg in args])
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/base/data/home/apps/s~dfp-playground/v1-0-9.412893970747758574/lib/suds/client.py", line 670, in process_reply
    raise WebFault(fault, replyroot)
WebFault: Server raised fault: '[ServerError.SERVER_ERROR @ ]'
```

**Comment by donovanfm** [comment]
Hi, Stephen.

This is related to the [other issue](https://github.com/googleads/googleads-php-lib/issues/557) you raised about makeTestNetwork failing. There was an internal change that broke this functionality, and we're looking into it now.

**Comment by donovanfm** [comment]
Hi, Stephen.

The internal issue has been resolved. I've tested DFP Playground's make test network functionality, and it worked for me. Can you verify if it's working for you as well? Thanks!

**Comment by donovanfm** [comment]
Closing this issue.
